[package]
name = "wasmlet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
env_logger = "0.11.6"
glob = "0.3.2"
log = "0.4.25"
thiserror = "2.0.11"
ureq = "3.0.0"
wasmer = "5.0.4"
